version: "3.9"
services:
  fastapi_app:
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ../src:/src
    depends_on:
      - db

  telegram_bot:
    build:
      context: ../
      dockerfile: ./docker/bot/Dockerfile
    container_name: telegram_bot
    volumes:
      - ../src:/src
    depends_on:
      - db

  service_http:
    build:
      context: ../
      dockerfile: ./docker/service/Dockerfile
    container_name: service_http
    volumes:
      - ../src:/src
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ../src/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Порт для внешнего доступа
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - fastapi_app

volumes:
  postgres_data:
