version: "3.9"
services:
  fastapi_app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./src/app:/app
    depends_on:
      - db

  telegram_bot:
    build:
      context: .
      dockerfile: ./docker/bot/Dockerfile
    container_name: telegram_bot
    volumes:
      - ./src/bot:/bot

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
